name: dart_fullstack
description: Dart Fullstack project
version: 0.0.1
environment:
  sdk: '>=2.0.0 <3.0.0'
dev_dependencies:
  aqueduct: ^3.0.0
  angular_test: ^2.1.0
  build_runner: ^1.1.2
  build_test: ^0.10.3
  build_web_compilers: ^0.4.4
  grinder: ^0.8.3
  test: ^1.5.1
  dart_dev: ^2.0.0